ShopManageProject/Models/Orders.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManageProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Orders
    {
        
        public Orders()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
        }
    
        public long OrderId { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> UserId { get; set; }
        //[Required]
        public string ShipName { get; set; }
        //[Required]
        [Phone]
        public string ShipMobile { get; set; }
       // [Required]
        public string ShipAddress { get; set; }
        //[Required]
        [EmailAddress]
        public string ShipEmail { get; set; }
        public Nullable<bool> Status { get; set; }
    
       
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        public virtual Users Users { get; set; }
    }
}

ShopManageProject/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShopManageProject.Models;
using ShopManageProject.Models.CartItem;
using ShopManageProject.Service;
using PagedList;

namespace ShopManageProject.Controllers
{
    public class OrdersController : Controller
    {
        private ShopManageDBEntities db = new ShopManageDBEntities();
        OrderService orderService = new OrderService();
        ProductsService productsService = new ProductsService();

        public ActionResult GetOrderByUser(long? userId,int ?page)
        {
            var orders = orderService.getOrderbyUser(userId);
            int pageNumber = (page ?? 1);

            orders = orders.ToList().ToPagedList(pageNumber, 10);

            
            if (Session["UserID"] != null && int.Parse(Session["UserID"].ToString()) == userId)
            {
                return View(orders);
               
            }
            return RedirectToAction("Login", "Login");
        }

        public ActionResult GetOrderDetail(long orderId)
        {
            var orderDetail = orderService.getListOrderDetail(orderId);
            if (Session["UserID"] != null)
            {
                return View(orderDetail.ToList());
                

            }
            return RedirectToAction("Login", "Login");
            
        }
        // GET: Orders/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Orders orders = orderService.detail(id);
            if (orders == null)
            {
                return HttpNotFound();
            }

            if (Session["UserID"] != null)
            {
                return View(orders);

            }
            return RedirectToAction("Login", "Login");
            
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
            ViewBag.UserId = new SelectList(db.Users, "UserId", "UserName");
            return View();
        }



        private string cartSession = "cart";

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrderId,ShipName,ShipMobile,ShipAddress,ShipEmail")] Orders orders)
        {
            long OrderId=0;
            var list = (List<CartItem>)Session[cartSession];


            if (ModelState.IsValid)
            {
                orders.UserId = long.Parse( Session["UserID"].ToString());
                orders.Status = false;
                orders.CreateDate = DateTime.Now;
                orderService.CreateOrder(orders);

                foreach( var item in orderService.getOrder())
                {
                   OrderId = item.OrderId;
   
                }

                foreach(var item in list)
                {
                    OrderDetail orderDetail = new OrderDetail();
                    orderDetail.OrderId = OrderId;
                    orderDetail.ProductId = item.Product.ProductId;
                    orderDetail.Quanlity = item.quantity;
                    orderDetail.Price = item.Product.PromotionPrice * item.quantity;
                    orderService.CreateOrderDetail(orderDetail);

                    Product product = productsService.detail(item.Product.ProductId);

                    product.Quanlity -= item.quantity;
                    product.CreateDate = DateTime.Now;
                    productsService.editProduct(product);

                    

                }
                CartController.count = 0;
                Session.Remove("count");
                Session.Remove("product");
                //Session.Remove(cartSession);
                return RedirectToAction("Details", new { id = OrderId});
                //return RedirectToAction("Index", "Products");

            }

            return View(list);
        }
        
        public ActionResult AcceptOrder(long orderId)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    orderService.updateOrder(orderId);
                    return RedirectToAction("GetOrderByUser", new { userId = Session["UserID"].ToString()});
                }
            }
            catch
            {
                return View("Error");
            }
            return View();
        }

        // GET: Orders/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Orders orders = db.Orders.Find(id);
            if (orders == null)
            {
                return HttpNotFound();
            }

            if (Session["UserID"] != null )
            {
                return View(orders);
            }
            return RedirectToAction("Login", "Login");
           
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OrderId,CreateDate,UserId,ShipName,ShipMobile,ShipAddress,ShipEmail,Status")] Orders orders)
        {
            if (ModelState.IsValid)
            {
                db.Entry(orders).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("GetOrderByUser", new { userId = Session["UserID"].ToString() });
            }
            
            return View(orders);
        }

        // GET: Orders/Delete/5
        //public ActionResult Delete(long? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Orders orders = db.Orders.Find(id);
        //    if (orders == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(orders);
        //}

        //// POST: Orders/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(long id)
        //{
        //    Orders orders = db.Orders.Find(id);
        //    db.Orders.Remove(orders);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ShopManageProject/Views/Orders/Create.cshtml
@model ShopManageProject.Models.Orders
@using ShopManageProject.Models.CartItem
@{
    var cart = (List<CartItem>)Session["cart"];
}

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Cart</h2>
<table class="table">
    <tr>
        <th>
            Code
        </th>
        <th>
            Tên Sản Phẩm
        </th>
        <th>
            Image
        </th>
        <th>
            Số Lượng
        </th>

        <th>
            Đơn Giá (Giá Khuyến Mại)
        </th>

        <th>
            Thành Tiền
        </th>

        <th></th>
    </tr>
    @{Nullable<decimal> total = 0; }
    @foreach (var item in cart)
    {
        <tr>
            <td>
                @item.Product.Code
            </td>
            <td>
                @item.Product.Name
            </td>
            <td>
                <img src="@item.Product.Image" width="100" height="90" />
            </td>
            <td>
                <input type="number" value="@item.quantity" style="width:150px" disabled />
            </td>
            <td>
                @String.Format("{0:0,0đ}", item.Product.PromotionPrice.GetValueOrDefault(0))
            </td>
            <td>
                @(String.Format("{0:0,0đ}", item.Product.PromotionPrice * item.quantity))
                @{total += item.Product.PromotionPrice * item.quantity;}

            </td>
        </tr>
    }
</table>
<br /><br />

@using (Html.BeginForm("Create", "Orders", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Orders</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Người Nhận", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShipName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShipName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Điện Thoại", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShipMobile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShipMobile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Địa Chỉ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShipAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShipAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Email", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShipEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShipEmail, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Order" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href="~/" class="btn btn-primary">Tiếp Tục Mua Hàng</a>
</div>

ShopManageProject/Views/Orders/Delete.cshtml
@model ShopManageProject.Models.Orders

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Orders</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShipName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShipName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShipMobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShipMobile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShipAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShipAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShipEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShipEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Users.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Users.UserName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ShopManageProject/Views/Orders/Details.cshtml
@model ShopManageProject.Models.Orders
@using ShopManageProject.Models.CartItem
@{
    var cart = (List<CartItem>)Session["cart"];
}
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h4><mark>Cảm ơn bạn đã đặt hàng!</mark></h4>
<h2>Chi tiết đơn hàng</h2>
<table class="table">
    <tr>
        <th>
            Code
        </th>
        <th>
            Tên Sản Phẩm
        </th>
        <th>
            Image
        </th>
        <th>
            Số Lượng
        </th>

        <th>
            Đơn Giá (Giá Khuyến Mại)
        </th>

        <th>
            Thành Tiền
        </th>

        <th></th>
    </tr>
    @{Nullable<decimal> total = 0; }
    @foreach (var item in cart)
    {
        <tr>
            <td>
                @item.Product.Code
            </td>
            <td>
                @item.Product.Name
            </td>
            <td>
                <img src="@item.Product.Image" width="100" height="90" />
            </td>
            <td>
                <input type="number" value="@item.quantity" style="width:150px" disabled />
            </td>
            <td>
                @String.Format("{0:0,0đ}", item.Product.PromotionPrice.GetValueOrDefault(0))
            </td>
            <td>
                @(String.Format("{0:0,0đ}", item.Product.PromotionPrice * item.quantity))
                @{total += item.Product.PromotionPrice * item.quantity;}

            </td>


        </tr>
                    }
</table>
<br /><br />


<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
           Ngày Tạo 
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>

        <dt>
           Tên Khách Hàng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShipName)
        </dd>

        <dt>
            Điện Thoại
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShipMobile)
        </dd>

        <dt>
           Địa Chỉ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShipAddress)
        </dd>

        <dt>
            Email
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShipEmail)
        </dd>

        <dt>
           Tên Tài Khoản
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Users.UserName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.OrderId }) |

    <a href="~/" class="btn btn-primary">Tiếp Tục Mua Hàng </a>
    @{
        Session.Remove("cart");
    }
</p>

ShopManageProject/Views/Orders/Edit.cshtml
@model ShopManageProject.Models.Orders

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Orders</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OrderId)

        <div class="form-group">
            @Html.LabelFor(model => model.CreateDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateDate, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.ShipName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShipName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShipName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShipMobile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShipMobile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShipMobile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShipAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShipAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShipAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShipEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShipEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShipEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ShopManageProject/Views/Orders/GetOrderByUser.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<ShopManageProject.Models.Orders>

@{
    ViewBag.Title = "GetOrderByUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Danh Sách Đơn Hàng Của Bạn</h2>


<table class="table">
    <tr>
        <th>
            Ngày Tạo
        </th>
        <th>
            Tên Khách Hàng
        </th>
        <th>
            Điện Thoại
        </th>
        <th>
            Địa Chỉ
        </th>
        <th>
            Email
        </th>
        <th width="150px">
            Trạng Thái
        </th>
        <th>
            Tên Tài Khoản
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CreateDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShipName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShipMobile)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShipAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShipEmail)
            </td>
            <td>
                @if (item.Status == true)
                {
                    <mark style="background:red;color:white">Đã Nhận Hàng</mark>
                }
                else
                {
                    <mark style="background:green;color:yellow">Đang Giao</mark>
                }

            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Users.UserName)
            </td>
            @if (item.Status == false)
            {
                <td>
                    <a href="~/Orders/AcceptOrder?orderId=@item.OrderId" class="btn btn-success">Xác Nhận</a>
                </td>
                <td>
                    <a href="~/Orders/AcceptOrder?orderId=@item.OrderId" class="btn btn-danger">Hủy Đơn Hàng</a>
                </td>
            }

            <td>
                <a href="~/Orders/GetOrderDetail?orderId=@item.OrderId" class="btn btn-primary">Chi Tiết</a>

            </td>
        </tr>
    }

</table>

<div id="pager">
    <p> Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount</p>
    @Html.PagedListPager(Model, page => Url.Action("GetOrderByUser", new { userId=@Session["UserID"].ToString(), page }))
</div>

ShopManageProject/Views/Orders/GetOrderDetail.cshtml
@model IEnumerable<ShopManageProject.Models.OrderDetail>
@{
    ViewBag.Title = "GetOrderDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@foreach (var item in Model)
{

<h2>Đơn Hàng [ID=@item.OrderId] (Khách Hàng : @item.Orders.ShipName)</h2>

    <h4>Ngày Đặt : @item.Orders.CreateDate </h4>
    break;
}
@{Nullable<decimal> total = 0; }
<table class="table">
    <tr>
        <th>
            Số Lượng
        </th>
        <th>
            Tổng Tiền
        </th>
        
        <th>
            Tên Sản Phẩm
        </th>
        <th>
            Image
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Quanlity)
        </td>
        <td>
            @String.Format("{0:0,0đ}", item.Price)
            @{total += item.Price;}
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Product.Name)
        </td>
        <td>
            <img src="@Html.DisplayFor(modelItem => item.Product.Image)" width="90" height="90" />
        </td>


    </tr>
    }


</table>

<br /><br />

<div class="container">
    <div class="col-md-4">
        Tổng Thiệt Hại :<mark style="color:white ;background-color:red">@(String.Format("{0:0,0đ}", total))</mark>
    </div>
    <div class="col-md-8">
        <a href="~/" class="btn btn-primary">Tiếp Tục Mua Hàng</a>

    </div>
</div>